### ISSUE TITLE
Install from from NPM. Error on use of pspb.

### ISSUE THREAD

**Issue by evilgeniusdev** [grantholle/powerschool-plugin-builder#1]
On installation of script from NPM (npm i -g powerschool-plugin-builder) the script crashes when attempting any operation.

```
pspb -h
/usr/local/lib/node_modules/powerschool-plugin-builder/lib/logger.js:7
module.exports = (quiet = false) => {
                        ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/powerschool-plugin-builder/lib/build.js:3:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

**Comment by grantholle** [comment]
Which version of Node are you using? I think you'll need version 6+ for this to work properly

**Comment by grantholle** [comment]
Closing because it seems to have gone stale. If you still have problems let me know.
